### ISSUE TITLE
Wait for performance improvements to the no-proxy level?

### ISSUE THREAD

**Issue by lootoos** [saiko-tech/mmproxy-rs#11]
no-proxy | 34662.036 | 53945.378 | 3173626.3 | 4630027.6 ( Mbps)

go-mmproxy | 27527.743 | 44128.818 | 2520408.4 | 3787491.3 ( Mbps)

mmproxy-rs | 27228.169 | 50173.384 | 2492924.1 | 4306284.7 ( Mbps)

mmproxy-rs:will it be possible to reach the no-proxy level?

Is it really possible for you to pull this off?

**Comment by seg6** [comment]
mmproxy-rs is already really fast since it literally moves memory pages around instead of copying data whenever possible.

It would be pretty hard to beat the current implementation without some sort of trade-off, e.g. making the minimum supported kernel version to something like 5.8 by introducing [io-uring](https://www.wikiwand.com/en/Io_uring).

**Comment by markus-wa** [comment]
@lootoos reaching no proxy is impossible - there will always be overhead.

well said @brkp

**Comment by lootoos** [comment]
well, adapt it to the version of linux 5.8+, because normal servers are already running on the kernel 5.15 ubuntu 22.04
