### ISSUE TITLE
how to perform a performance test of mmproxy-rs?

### ISSUE THREAD

**Issue by lootoos** [saiko-tech/mmproxy-rs#7]
iperf server install on vds?
 iperf client on home pc? 
 next, run iperf clinet - by specifying the address of the iperf server?
 Are there any ways to test TCP mmproxy-rs?
 What are the commands for testing TCP mmproxy-rs?

**Comment by seg6** [comment]
- Start an echo server in the same machine as mmproxy-rs is running and then point mmproxy-rs to it
- Install `tcpkali` and run the following command on that same machine:
```
tcpkali -c 50 -T 10s -e1 'PROXY TCP4 127.0.0.1 127.0.0.1 \{connection.uid} $ECHOSERVERPORT\r\n' -m 'PING\r\n' 127.0.0.1:$MMPROXYPORT
```

Please note that we have an open issue (#4) that aims to improve the throughput of the TCP proxy by approximately 100%, but I have not yet had the time to fully work on it because of upcoming final exams.

**Comment by lootoos** [comment]
Start the echo server on the same machine running mmproxy-rs - how to start the echo server?

**Comment by seg6** [comment]
One option for setting up an echo server is to use [ncat](https://nmap.org/ncat/). To do so, simply enter the command `ncat -e /bin/cat -kl 1122` in the terminal. This will start an echo server on port 1122. Another option, which is faster but requires a bit more setup, is [bpf-echo](https://github.com/path-network/bpf-echo). If you want to use this option, you can follow the installation instructions on the GitHub page.

**Comment by lootoos** [comment]
I run "ncat -e /bin/cat -kl 1122" which command should I enter next to check the performance?

**Comment by markus-wa** [comment]
I think I will add more detailed benchmarking docs when I have some time

**Comment by lootoos** [comment]
When should I wait ?
